version: "3"
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      # Inicialização do banco
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
